remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

title: "Working with Tobey"
description: "Tobey Aumann is a leadership coach with 20 years on the people and product side of tech."
